### ISSUE TITLE
About LCD usage 

### ISSUE THREAD

**Issue by Zaryob** [pierreyvesbaloche/PiHQCam#2]
Im using 3.5 inch waveshare screen https://www.waveshare.com/3.5inch-rpi-lcd-c.htm

Is there any chance to use it with GPIO ports
Have you ever tried.

**Comment by pierreyvesbaloche** [comment]
Unfortunately u do not have access to such screen. 
I guess it could be possible but would require changes on both the 3Dscreen holder as well as the controller.

**Comment by Zaryob** [comment]
Thanks
